[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo ='scrooloose/nerdtree'

[[plugins]]
repo ='jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
